### ISSUE TITLE
regression:  zustand.createStore is not a function in 4.3.4

### ISSUE THREAD

**Issue by grabbou** [pmndrs/zustand#1662]
## Summary

After upgrading to `4.3.4` from `4.3.3`, I am getting the following error:
```
TypeError: (0 , zustand_1.createStore) is not a function
```

## Link to reproduction

You can check PR in Uniswap/web3-react https://github.com/Uniswap/web3-react/pull/767 where we're running into this issue. I demonstrated first commit on that PR to fail tests after upgrading to 4.3.4 and another commit to pass tests after downgrading explicitly to 4.3.3.

Hope that helps.

**Comment by dai-shi** [comment]
Our apologies for the regression.
#1661 will fix it.
Please pin version meanwhile.

**Comment by grabbou** [comment]
No worries, thank you for the quick fix
