### PR TITLE
fix: add explicity export paths for cjs

### LINKED ISSUE #1563: Error with zustand exports in parcel production builds
## Summary

A new error occurred in production builds using `zustand@4.3.2` and [`parcel`](https://github.com/parcel-bundler/parcel). This error does not occur in `zustand@4.3.1` and is probably related to #1531.

The following error is displayed in the console when serving a production build:
```
Uncaught TypeError: (0 , i.create) is not a function
    at app.js:3:22
```
Development server works fine.

This issue is similar to #1475.

## Link to reproduction

https://github.com/nicobohne/zustand-parcel-reproduction
https://codesandbox.io/p/github/nicobohne/zustand-parcel-reproduction/main

## Check List

Please do not ask questions in issues.

- [X] I've already opened a [discussion](https://github.com/pmndrs/zustand/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [X] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

### PR DESCRIPTION
**Pull request by barelyhuman**
## Related Issues or Discussions

Fixes #1563 

## Summary

Manually adds a set of `module.exports` for each file that needs a the CJS patch for exports. 
This is temporary and will be removed once zustand's API are all named instead of mixed.

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Review by dai-shi — APPROVED** [review]
Thanks so much for your investigation!!
